<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="module" src="/js/config.js"></script>
  <link rel="icon" sizes="32x32" href="/favicon.ico">
  <meta name="theme-color" content="#ffffff">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="stylesheet" href="/css/estilos.css">
</head>
<body>
  <layout-cajon>
    <mi-nav slot="nav"></mi-nav>
    <ctrl-diapositiva slot="toolbar"></ctrl-diapositiva>
    <h1>try-catch</h1>
    <div class="marco-lectura">
      <figure class="columnas2">
        <img src="img/try-catch.svg" alt="Diagrama de try-catch."
          style="max-width: 350px;">
        <img src="img/try-error-catch.svg"
          alt="Diagrama de try-catch con error."
          style="max-width: 350px;">
      </figure>
      <p>
        Para procesar los errores, la instrucción
        <code class="language-javascript">throw</code>
        debe ejecutarse dentro de las llaves de
        <code class="language-javascript">try</code>.
      </p>
      <p>
        Si llega al final de las llaves de
        <code class="language-javascript">try</code>
        sin lanzar ninguna excepción, la cláusula
        <code class="language-javascript">catch</code>
        y las
        <i>instrucciones para procesar la excepción</i>
        no se ejecutan, continuando con las instrucciones que
        vengan después de la estructura completa
        <code class="language-javascript">try</code>
        -
        <code class="language-javascript">catch</code>.
      </p>
      <p>
        Si se lanza una excepción dentro de las llaves de
        <code class="language-javascript">try</code>,
        las restantes instrucciones hasta cerrar llaves no se ejecutan.
        Se toma la excepción lanzada; a este proceso se le llama
        <dfn>atrapar la excepción</dfn>. La excepción atrapada se pasa
        como parámetro a la cláusula
        <code class="language-javascript">catch</code>
        el flujo normal se restablece y se ejecutan las
        <i>instrucciones para procesar la excepción</i>,
        continuando con las instrucciones que vengan después de la
        estructura completa
        <code class="language-javascript">try</code>
        -
        <code class="language-javascript">catch</code>.
      </p>
      <p>
        <a href="http://pythontutor.com/javascript.html#code=try%20%7B%0A%20%20console.log%28%22Ejecuta%20bien.%22%29%3B%0A%7D%20catch%20%28e%29%20%7B%0A%20%20console.log%28%22Esto%20no%20se%20hace.%22%29%3B%0A%7D%0Aconsole.log%28%22Contin%C3%BAa%20normal.%22%29%3B%0Atry%20%7B%0A%20%20console.log%28%22Intenta%20seguir.%22%29%3B%0A%20%20throw%20new%20Error%28%22Fallo.%22%29%3B%0A%20%20console.log%28%22Esto%20no%20se%20hace%22%29%3B%0A%7D%20catch%20%28e%29%20%7B%0A%20%20console.log%28%22Procesa%20el%20error%3A%22,%0A%20%20%20%20e.message%29%3B%0A%7D%0Aconsole.log%28%22Adios.%22%29%3B&curInstr=0&mode=display&origin=opt-frontend.js&py=js&rawInputLstJSON=%5B%5D"
          target="_blank">Ejemplo animado de try-catch.</a>
      </p>
    </div>
    <mi-footer></mi-footer>
  </layout-cajon>
</body>
</html>